{{- include "reflektor.usedExports" . }}
{{- if .reflektorExportUsesNfs }}
apiVersion: v1
kind: Service
metadata:
  name: nfs
spec:
  type: ClusterIP
  ports:
    - port: 2049
      protocol: TCP
  selector:
    app.kubernetes.io/name: reflektor
    app.kubernetes.io/component: main
{{- end -}}